# File: .github/workflows/cypress.yml

name: Cypress

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          install: true
          runTests: true
